version: '2' 
services:
  web:
    build: Dockerfiles/anaconda3
    env_file: .env
    volumes:
      - ./:/mediapy
    command: bash -c "mkdir -p mediapy/notebooks && 
                      /opt/conda/bin/jupyter notebook --notebook-dir=mediapy/notebooks --ip='*' --port=8888 --no-browser --NotebookApp.token=github --allow-root" 
    ports:
      - 8888:8888
      - 5000:5000
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    build: Dockerfiles/mongo
    env_file: .env
    volumes:
      - ./.data/mongo:/data/db
      - ./.dump/mongo:/dump
